Script started on Fri 06 Nov 2015 12:20:32 PM PST
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls #
a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ ls # -a
a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ ls# -a
a.out  commented_command.script
*** ERROR: exec failed
[qjuar001@hammer.cs.ucr.edu]$ ls #-a
a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ ls -a || #mkdir testFile
.  ..  a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ ls && #mkdir testFile; ls
a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ mkdir test#File; ls
*** ERROR: exec failed
a.out  commented_command.script	 test
[qjuar001@hammer.cs.ucr.edu]$ rm -rf test && echo he#llo
he
*** ERROR: exec failed
[qjuar001@hammer.cs.ucr.edu]$ echo the || command #hshouldrprint[D^[[D^[[D^[[D^[[D^[[D
the
[qjuar001@hammer.cs.ucr.edu]$ echo the && command # should print
the
*** ERROR: exec failed
[qjuar001@hammer.cs.ucr.edu]$ # ls -a
.  ..  a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ #ls -a
.  ..  a.out  commented_command.script
[qjuar001@hammer.cs.ucr.edu]$ vi test.cpp
[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  commented_command.script	 test.cpp
[qjuar001@hammer.cs.ucr.edu]$ catttest.cppt&&tcp test.cpp test#2.cpp; ls
This is the test1 file
*** ERROR: exec failed
a.out  commented_command.script	 test  test.cpp
[qjuar001@hammer.cs.ucr.edu]$ f# ls -a
[qjuar001@hammer.cs.ucr.edu]$ cat test #; echo #hello
This is the test1 file
[qjuar001@hammer.cs.ucr.edu]$ echo #hello

[qjuar001@hammer.cs.ucr.edu]$ echo hello#
hello
[qjuar001@hammer.cs.ucr.edu]$ exit
[qjuar001@hammer bin]$ exit
exit

Script done on Fri 06 Nov 2015 12:33:38 PM PST
