Script started on Fri 06 Nov 2015 12:43:47 PM PST
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  exit.script
[qjuar001@hammer.cs.ucr.edu]$ exit
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls || exit
a.out  exit.script
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls && exit
a.out  exit.script
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls; # exit
a.out  exit.script
[qjuar001@hammer.cs.ucr.edu]$ echo hello && ls || mkdir testFile; mkdir testFile2 || exit || ls -a
hello
a.out  exit.script
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  exit.script  testFile2
[qjuar001@hammer.cs.ucr.edu]$ rm -rfttestFile2 exit
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls exit
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ echo exit
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ echo noexit
noexit
[qjuar001@hammer.cs.ucr.edu]$ mkdir testexitFile && ls
a.out  exit.script  testexitFile  testFile2
[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  exit.cpp	 exit.script  testexitFile  testFile2
[qjuar001@hammer.cs.ucr.edu]$ rmmexit.cpp test
[qjuar001@hammer.cs.ucr.edu]$ rm -rf testexitFile
[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  exit.script  testFile2
[qjuar001@hammer.cs.ucr.edu]$ exit
[qjuar001@hammer bin]$ exit
exit

Script done on Fri 06 Nov 2015 12:50:25 PM PST
