Script started on Fri 06 Nov 2015 11:49:09 AM PST
[qjuar001@hammer bin]$ ./a.out

rshell Copyright (C) 2015 Queston Juarez & Mark Spencer
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

[qjuar001@hammer.cs.ucr.edu]$ ls; echo multiple commands! Yay!
a.out  multi_command.script  testFile  testFile2
multiple commands! Yay!
[qjuar001@hammer.cs.ucr.edu]$ ls testFile testFile2; git branch; echo third command
testFile:
test.cpp

testFile2:
test2.cpp
* exec
  master
third command
[qjuar001@hammer.cs.ucr.edu]$ rm -rfttestFile2 || rm -rf testFile; ls
a.out  multi_command.script  testFile
[qjuar001@hammer.cs.ucr.edu]$ ls
a.out  multi_command.script  testFile
[qjuar001@hammer.cs.ucr.edu]$ ls -a; cat test3.cpp && cphtest3.cpp test4.cpp || mv test3.cpp test4.cpp; ls
.  ..  a.out  multi_command.script  test3.cpp  testFile	 testFile3
This is my third test.cpp file!
a.out  multi_command.script  test3.cpp	test4.cpp  testFile  testFile3
[qjuar001@hammer.cs.ucr.edu]$ mv test	  test3.cpp	   testFile3 && ls; rm -rfttestFile3 && rm testFile33||secho The last command failed so now this one is running || ls || ls -a && echo that was a long chain of commands
a.out  multi_command.script  test4.cpp	testFile  testFile3
rm: cannot remove `testFile3': No such file or directory
The last command failed so now this one is running
.  ..  a.out  multi_command.script  test4.cpp  testFile
that was a long chain of commands
[qjuar001@hammer.cs.ucr.edu]$ ls|| echo hello
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ ls ||echo hello
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ ls||echo hello
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ ls&&echo hello
a.out  multi_command.script  test4.cpp	testFile
hello
[qjuar001@hammer.cs.ucr.edu]$ ls&& echo hello
a.out  multi_command.script  test4.cpp	testFile
hello
[qjuar001@hammer.cs.ucr.edu]$ ls &&echo hello
a.out  multi_command.script  test4.cpp	testFile
hello
[qjuar001@hammer.cs.ucr.edu]$ ls ; || echo hello
a.out  multi_command.script  test4.cpp	testFile
hello
[qjuar001@hammer.cs.ucr.edu]$ ls ; && echo hello
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ ls ||
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ ls &&
a.out  multi_command.script  test4.cpp	testFile
[qjuar001@hammer.cs.ucr.edu]$ rm || -rf testFile
rm: missing operand
Try `rm --help' for more information.
*** ERROR: exec failed
[qjuar001@hammer.cs.ucr.edu]$ rm testFile || ls && rm -rf testFile;|| ls; ls--a
rm: cannot remove `testFile': Is a directory
a.out  multi_command.script  test4.cpp	testFile
.  ..  a.out  multi_command.script  test4.cpp
[qjuar001@hammer.cs.ucr.edu]$ cat test4.cpp && fg || cp test4.cpp test5.cpp && ls -a
This is my third test.cpp file!
*** ERROR: exec failed
.  ..  a.out  multi_command.script  test4.cpp  test5.cpp
[qjuar001@hammer.cs.ucr.edu]$ rm test4.cpp test5.cpp & ls
a.out  multi_command.script
[qjuar001@hammer.cs.ucr.edu]$ ls | echo oh no
a.out  multi_command.script
oh no
[qjuar001@hammer.cs.ucr.edu]$ exit
[qjuar001@hammer bin]$ exit
exit

Script done on Fri 06 Nov 2015 12:10:03 PM PST
