#makefile that compiles command shell

all: main.cpp commands.o
	g++ -W -Wall -Werror -ansi -pedantic main.cpp commands.o

rshell: main.cpp commands.o
	g++ -W -Wall -Werror -ansi -pedantic main.cpp commands.o

cmds: commands.cpp
	g++ -c -W -Wall -Werror -ansi -pedantic commands.cpp


