#makefile that compiles command shell

all: main.cpp commands.cpp 
	g++ -Wall -Werror -ansi -pedantic -o rshell main.cpp commands.cpp
	mv rshell ../bin
rshell: main.cpp commands.cpp
	g++ -Wall -Werror -ansi -pedantic -o rshell main.cpp commands.cpp
	mv rshell ../bin
